<a href="https://colab.research.google.com/github/mamontoff2018-lgtm/google-colab/blob/main/MO9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('50_Startups.csv')
dataset.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
print ("Матрица признаков"); print(X[:5])
print ("Зависимая переменная"); print(y[:5])

Матрица признаков
[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
Зависимая переменная
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
print("Зависимая переменная до обработки")
print(y)
y = labelencoder_y.fit_transform(y)
print("Зависимая переменная после обработки")
print(y)

Зависимая переменная до обработки
[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]
Зависимая переменная после обработки
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [3])],
    remainder='passthrough'
)
X = ct.fit_transform(X)
print("Перекодировка категориального признака")
print(X[:4,:])

Перекодировка категориального признака
[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]]


In [ ]:
X = X[:, 1:]
print(X[:4,:])

[[0.0 1.0 165349.2 136897.8 471784.1]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 144372.41 118671.85 383199.62]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)

[22.73971792 31.79851398 32.76702713 10.17872713 48.95244293 25.07783798
  7.62074212 20.43498693 25.32328448 45.16861644]


In [ ]:
import statsmodels.api as sm
import numpy as np
X = np.array(X, dtype=np.float64, copy=True)

X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

X_opt = X[:, [0, 1, 2, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.023
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5606
Date:                Sun, 12 Apr 2026   Prob (F-statistic):              0.575
Time:                        15:22:03   Log-Likelihood:                -203.83
No. Observations:                  50   AIC:                             413.7
Df Residuals:                      47   BIC:                             419.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4118      0.892      6.068      0.000       3.617       7.206
x1             5.4118      0.892      6.068      0.000       3.617       7.206
x2             5.4118      0.892      6.068      0.000       3.617       7.206
x3             5.4118      0.892      6.068      0.000       3.617       7.206
x4             5.3529      5.124      1.045      0.301      -4.955      15.660
x5             3.3529      5.045      0.665      0.510      -6.797      13.503
==============================================================================
Omnibus:                       10.210   Durbin-Watson:                   0.069
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                2.849
Skew:                           0.060   Prob(JB):                        0.241
Kurtosis:                       1.837   Cond. No.                     7.13e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.15e-36. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
X_opt = X[:, [0, 1, 3, 4, 5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.023
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5606
Date:                Sun, 12 Apr 2026   Prob (F-statistic):              0.575
Time:                        15:23:38   Log-Likelihood:                -203.83
No. Observations:                  50   AIC:                             413.7
Df Residuals:                      47   BIC:                             419.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.2157      1.189      6.068      0.000       4.823       9.608
x1             7.2157      1.189      6.068      0.000       4.823       9.608
x2             7.2157      1.189      6.068      0.000       4.823       9.608
x3             5.3529      5.124      1.045      0.301      -4.955      15.660
x4             3.3529      5.045      0.665      0.510      -6.797      13.503
==============================================================================
Omnibus:                       10.210   Durbin-Watson:                   0.069
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                2.849
Skew:                           0.060   Prob(JB):                        0.241
Kurtosis:                       1.837   Cond. No.                     3.64e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.21e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
X_opt = X[:, [0, 3, 4, 5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.023
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5606
Date:                Sun, 12 Apr 2026   Prob (F-statistic):              0.575
Time:                        15:23:49   Log-Likelihood:                -203.83
No. Observations:                  50   AIC:                             413.7
Df Residuals:                      47   BIC:                             419.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         10.8235      1.784      6.068      0.000       7.235      14.412
x1            10.8235      1.784      6.068      0.000       7.235      14.412
x2             5.3529      5.124      1.045      0.301      -4.955      15.660
x3             3.3529      5.045      0.665      0.510      -6.797      13.503
==============================================================================
Omnibus:                       10.210   Durbin-Watson:                   0.069
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                2.849
Skew:                           0.060   Prob(JB):                        0.241
Kurtosis:                       1.837   Cond. No.                     6.53e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.61e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
X_opt = X[:, [0, 3, 5]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.020
Method:                 Least Squares   F-statistic:                   0.02970
Date:                Sun, 12 Apr 2026   Prob (F-statistic):              0.864
Time:                        15:23:59   Log-Likelihood:                -204.40
No. Observations:                  50   AIC:                             412.8
Df Residuals:                      48   BIC:                             416.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.1212      1.282      9.458      0.000       9.544      14.698
x1            12.1212      1.282      9.458      0.000       9.544      14.698
x2             0.7576      4.396      0.172      0.864      -8.081       9.596
==============================================================================
Omnibus:                       11.933   Durbin-Watson:                   0.006
Prob(Omnibus):                  0.003   Jarque-Bera (JB):                3.018
Skew:                          -0.001   Prob(JB):                        0.221
Kurtosis:                       1.796   Cond. No.                     5.10e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.09e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
X_opt = X[:, [0, 3]]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                      -0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Sun, 12 Apr 2026   Prob (F-statistic):                nan
Time:                        15:24:11   Log-Likelihood:                -204.42
No. Observations:                  50   AIC:                             410.8
Df Residuals:                      49   BIC:                             412.7
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.2500      1.031     11.884      0.000      10.179      14.321
x1            12.2500      1.031     11.884      0.000      10.179      14.321
==============================================================================
Omnibus:                       12.878   Durbin-Watson:                   0.005
Prob(Omnibus):                  0.002   Jarque-Bera (JB):                3.005
Skew:                           0.000   Prob(JB):                        0.223
Kurtosis:                       1.799   Cond. No.                     5.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.98e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [ ]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.api as sm

# Загрузка данных
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['MedHouseVal'] = housing.target

print("Датасет загружен!")
print(f"Размер: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"\nПризнаки: {housing.feature_names}")
print(f"Целевая переменная: MedHouseVal (медианная цена дома в $100k)")
print(f"\nПервые 5 строк:")
print(df.head())

Датасет загружен!
Размер: 20640 строк, 9 столбцов

Признаки: ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
Целевая переменная: MedHouseVal (медианная цена дома в $100k)

Первые 5 строк:
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422  


In [ ]:
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

print(f"\nМатрица признаков X: {X.shape}")
print(f"Целевая переменная y: {y.shape}")


Матрица признаков X: (20640, 8)
Целевая переменная y: (20640,)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\nОбучающая выборка: {X_train.shape[0]} объектов")
print(f"Тестовая выборка: {X_test.shape[0]} объектов")


Обучающая выборка: 16512 объектов
Тестовая выборка: 4128 объектов


In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)



LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mse = mean_squared_error(y_test, y_pred)

print(f"Качество модели:")
print(f"R² = {r2:.4f} (модель объясняет {r2*100:.1f}% вариации)")
print(f"RMSE = {rmse:.4f} (в единицах $100k)")
print(f"MSE = {mse:.4f}")

Качество модели:
R² = 0.5758 (модель объясняет 57.6% вариации)
RMSE = 0.7456 (в единицах $100k)
MSE = 0.5559


In [ ]:
X_train_sm = sm.add_constant(X_train)
X_opt = X_train_sm.copy()
SL = 0.05

print(f"Исходное количество признаков: {X_opt.shape[1] - 1}")

step = 1
while True:
    model_sm = sm.OLS(y_train, X_opt).fit()
    p_values = model_sm.pvalues.iloc[1:]
    max_p = p_values.max()

    if max_p > SL:
        col_to_remove = p_values.idxmax()
        X_opt = X_opt.drop(columns=[col_to_remove])
        print(f"Шаг {step}: удален '{col_to_remove}' (p-value = {max_p:.6f})")
        step += 1
    else:
        break

print(f"\nОсталось значимых признаков: {X_opt.shape[1] - 1}")
print(f"Финальный R²: {model_sm.rsquared:.4f}")
print(f"Скорректированный R²: {model_sm.rsquared_adj:.4f}")

Исходное количество признаков: 8
Шаг 1: удален 'Population' (p-value = 0.698990)

Осталось значимых признаков: 7
Финальный R²: 0.6125
Скорректированный R²: 0.6124


In [ ]:
X_test_sm = sm.add_constant(X_test)
X_test_opt = X_test_sm[X_opt.columns]
y_pred_final = model_sm.predict(X_test_opt)
r2_final = r2_score(y_test, y_pred_final)

print(f"LinearRegression (все 8 признаков): R² = {r2:.4f}")
print(f"После Backward Elimination ({X_opt.shape[1]-1} признаков): R² = {r2_final:.4f}")

LinearRegression (все 8 признаков): R² = 0.5758
После Backward Elimination (7 признаков): R² = 0.5757
